version: "3.9"

services:
  java-service:
    build:
      context: ./RentalService
      dockerfile: Dockerfile
    container_name: java-service
    ports:
      - "8080:8080"

  php-service:
    build:
      context: ./PhpService
      dockerfile: Dockerfile
    container_name: php-service
    ports:
      - "8081:80"
